// ESLint for the whole monorepo (run from the root: `pnpm lint`).
//
// Besides correctness rules, this enforces the architecture from the spec:
//  - packages never depend on apps (SRS §63.1)
//  - web: a feature never reaches into another feature, and shared code never depends on
//    features or routes (§17.3); server calls go through lib/api.ts
//  - api: code outside a module uses only the module's index.ts, and shared code is the bottom
//    layer (§19.2, §63.1); the domain layer imports no frameworks (§19.2)
//  - web, mobile and the component library: no hard-coded user-facing text (I18N-001)
//  - mobile: the same feature/shared layering as the web app
import js from '@eslint/js';
import boundaries from 'eslint-plugin-boundaries';
import i18next from 'eslint-plugin-i18next';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

const TS = ['**/*.{ts,tsx}'];
const WEB_SRC = ['apps/web/src/**/*.{ts,tsx}', 'packages/ui/src/**/*.{ts,tsx}'];
const TESTS = ['**/*.test.{ts,tsx}', '**/test/**'];

/** "Unless it is that element's index file": other elements are reached through their public API. */
const notOwn = (capture) => `!{{ from.element.captured.${capture} }}`;

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/generated/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/.turbo/**',
      'docs/**',
      'database/**',
      'apps/docs/dist/**',
      'packages/db/src/schema.ts', // generated by drizzle-kit pull, then maintained as data
      'packages/db/src/relations.ts',
      '**/storybook-static/**',
      '**/.expo/**',
      'apps/mobile/src/db/migrations/**', // generated by drizzle-kit
    ],
  },
  js.configs.recommended,

  // --- TypeScript ------------------------------------------------------------------------------
  {
    files: TS,
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      eqeqeq: ['error', 'always'],
      'no-console': 'error',
    },
  },
  {
    // Tests may use loose typing for fakes and mocks.
    files: TESTS,
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },

  {
    // Tool config files belong to no tsconfig project: lint them without type information.
    files: ['**/vitest*.config.ts', 'packages/db/drizzle.config.ts'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: { parserOptions: { projectService: false, project: null } },
  },

  // --- Plain JavaScript (build and CI scripts) ------------------------------------------------------
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: { globals: { ...globals.node } },
    rules: { 'no-console': 'off' },
  },

  // --- Web ----------------------------------------------------------------------------------------
  {
    files: WEB_SRC,
    languageOptions: { globals: { ...globals.browser } },
    plugins: { 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y, i18next },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      // User-facing text comes from src/i18n (I18N-001). Attribute text that users read counts too.
      'i18next/no-literal-string': [
        'error',
        {
          mode: 'jsx-only',
          'jsx-attributes': { include: ['aria-label', 'title', 'alt', 'placeholder'] },
        },
      ],
      // Server calls go through lib/api.ts (typed GraphQL + REST helpers), not ad-hoc fetch.
      'no-restricted-globals': [
        'error',
        { name: 'fetch', message: 'Call the API through src/lib/api.ts (gql / rest).' },
      ],
    },
  },
  {
    // lib/api.ts and lib/auth.ts are the two places that talk HTTP.
    files: [
      'apps/web/src/lib/api.ts',
      'apps/web/src/lib/auth.ts',
      ...TESTS.map((p) => `apps/web/src/${p}`),
    ],
    rules: { 'no-restricted-globals': 'off', 'i18next/no-literal-string': 'off' },
  },
  {
    // TanStack Router guards redirect by throwing `redirect(...)`, which is not an Error.
    files: ['apps/web/src/routes/**/*.tsx'],
    rules: {
      '@typescript-eslint/only-throw-error': [
        'error',
        { allow: [{ from: 'package', package: '@tanstack/router-core', name: 'Redirect' }] },
      ],
    },
  },
  {
    // Stories and tests show sample content; the components themselves take all text as props.
    files: ['packages/ui/src/**/*.stories.tsx', ...TESTS.map((p) => `packages/ui/src/${p}`)],
    rules: { 'i18next/no-literal-string': 'off' },
  },
  // --- Mobile -------------------------------------------------------------------------------------
  {
    files: ['apps/mobile/src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks, i18next },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'i18next/no-literal-string': [
        'error',
        {
          mode: 'jsx-only',
          'jsx-attributes': { include: ['accessibilityLabel', 'accessibilityHint'] },
        },
      ],
    },
  },
  {
    files: TESTS.map((p) => `apps/mobile/src/${p}`),
    rules: { 'i18next/no-literal-string': 'off' },
  },
  {
    files: ['packages/ui/.storybook/**/*.{ts,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
  },

  // --- Architecture boundaries ----------------------------------------------------------------------
  {
    files: TS,
    plugins: { boundaries },
    settings: {
      'import/resolver': {
        typescript: { project: ['apps/*/tsconfig.json', 'packages/*/tsconfig.json'] },
      },
      'boundaries/elements': [
        { type: 'package', pattern: 'packages/*', capture: ['name'] },
        { type: 'web-feature', pattern: 'apps/web/src/features/*', capture: ['feature'] },
        { type: 'web-route', pattern: 'apps/web/src/routes' },
        {
          type: 'web-shared',
          pattern: [
            'apps/web/src/components',
            'apps/web/src/lib',
            'apps/web/src/stores',
            'apps/web/src/i18n',
            'apps/web/src/generated',
            'apps/web/src/test',
          ],
        },
        { type: 'mobile-feature', pattern: 'apps/mobile/src/features/*', capture: ['feature'] },
        { type: 'mobile-route', pattern: 'apps/mobile/src/app' },
        {
          type: 'mobile-shared',
          pattern: [
            'apps/mobile/src/components',
            'apps/mobile/src/lib',
            'apps/mobile/src/stores',
            'apps/mobile/src/theme',
            'apps/mobile/src/i18n',
            'apps/mobile/src/db',
            'apps/mobile/src/test',
          ],
        },
        { type: 'api-module', pattern: 'apps/api/src/modules/*', capture: ['module'] },
        { type: 'api-shared', pattern: 'apps/api/src/shared' },
        {
          type: 'api-core',
          pattern: [
            'apps/api/src/graphql',
            'apps/api/src/rest',
            'apps/api/src/events',
            'apps/api/src/scheduler',
          ],
        },
      ],
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'allow',
          policies: [
            {
              // Packages are shared by every app, so they must not depend on any of them.
              from: { element: { type: 'package' } },
              disallow: { to: { element: { type: ['web-*', 'api-*', 'mobile-*'] } } },
            },
            {
              // A feature uses another feature only through its index file.
              from: { element: { type: 'web-feature' } },
              disallow: {
                to: {
                  element: {
                    type: 'web-feature',
                    captured: { feature: notOwn('feature') },
                    fileInternalPath: '!index.{ts,tsx}',
                  },
                },
              },
            },
            {
              // Shared web code sits below features and routes.
              from: { element: { type: 'web-shared' } },
              disallow: { to: { element: { type: ['web-feature', 'web-route'] } } },
            },
            {
              from: { element: { type: 'web-feature' } },
              disallow: { to: { element: { type: 'web-route' } } },
            },
            {
              // Mobile follows the same layering: features meet only through their index file, and
              // shared code sits below features and routes.
              from: { element: { type: 'mobile-feature' } },
              disallow: {
                to: {
                  element: {
                    type: 'mobile-feature',
                    captured: { feature: notOwn('feature') },
                    fileInternalPath: '!index.{ts,tsx}',
                  },
                },
              },
            },
            {
              from: { element: { type: 'mobile-shared' } },
              disallow: { to: { element: { type: ['mobile-feature', 'mobile-route'] } } },
            },
            {
              // Modules talk to each other only through their index.ts (their public surface).
              from: { element: { type: 'api-module' } },
              disallow: {
                to: {
                  element: {
                    type: 'api-module',
                    captured: { module: notOwn('module') },
                    fileInternalPath: '!index.ts',
                  },
                },
              },
            },
            {
              // Everything outside a module sees only its index.ts too.
              from: { element: { type: '!api-module' } },
              disallow: { to: { element: { type: 'api-module', fileInternalPath: '!index.ts' } } },
            },
            {
              // Shared infrastructure is the bottom layer of the API.
              from: { element: { type: 'api-shared' } },
              disallow: { to: { element: { type: ['api-module', 'api-core'] } } },
            },
          ],
        },
      ],
    },
  },
  {
    // The domain layer is plain TypeScript: no frameworks, drivers or ORMs (SRS §19.2).
    files: ['apps/api/src/modules/*/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            'express',
            'graphql',
            'graphql-yoga',
            'pg',
            'drizzle-orm',
            'ioredis',
            'bullmq',
            '@ie/db',
          ].map((name) => ({
            name,
            message: 'The domain layer must not depend on frameworks or infrastructure.',
          })),
          patterns: [
            {
              group: ['drizzle-orm/*', '**/infrastructure/**', '**/interface/**'],
              message: 'The domain layer must not depend on frameworks or infrastructure.',
            },
          ],
        },
      ],
    },
  },
);
